### ISSUE TITLE
파일정보 가져오는 함수 기술설명입니다.

### ISSUE THREAD

**Issue by hongjinhyeok** [yjosp95/Project2#1]
stat함수는 파일의 크기, 파일의 권한, 파일의 생성일시, 파일의 최종 변경일 등, 파일의 상태나 파일의 정보를 얻는 함수입니다. 또 symbolic link인 파일을 path로 넘기면 그 원본 파일의 정보를 얻을 수 있습니다. lstat함수는 symbolic link 파일 자신의 정보를 얻을 수 있습니다.

**Comment by yjosp95** [comment]
파일 정보 가져오는 다른 함수는 있나요?

**Comment by Jeongyonghoon** [comment]
시스템프로그래밍이랑 내용이 겹치네요 이해했습니다!

**Comment by kimmincheol-kor** [comment]
좋은 정보 감사합니다

**Comment by hongjinhyeok** [comment]
> 파일 정보 가져오는 다른 함수는 있나요?

네! lstat이라는 함수가 있고 사용법은 같습니다.
