### ISSUE TITLE
5번함수 코드 리뷰

### ISSUE THREAD

**Issue by Jeongyonghoon** [yjosp95/Project2#18]
각 파일의 크기를 비교하는 함수 작성 완료하였고 local 우분투에서
정상 작동하는것 확인했습니다! milestone issue모두 close되면 pull request하겠습니다!

**Comment by hongjinhyeok** [comment]
코드 문제없습니다.

**Comment by yjosp95** [comment]
리퀘스트 보내주세요!

**Comment by kimmincheol-kor** [comment]
문제없습니다.
