### ISSUE TITLE
파일 수정시간 비교 함수 : 기술 조사

### ISSUE THREAD

**Issue by kimmincheol-kor** [yjosp95/Project2#2]
파일의 정보를 가져오는 함수를 통해 stat 구조체를 사용하여 파일의 정보를 가져오고, 시간 정보를 가져오는 함수를 통해 tm 구조체를 사용하여 시간 정보를 가져온다.
비교할 2개의 파일의 tm 구조체의 tm_hour, tm_min 데이터를 사용하여 두 개의 파일의 수정 시간을 비교한다.

**Comment by hongjinhyeok** [comment]
확인했습니다 질문 없습니다.

**Comment by yjosp95** [comment]
네 알겠습니다 사용하시면 될 것 같습니다.

**Comment by Jeongyonghoon** [comment]
확인했어요~
