### ISSUE TITLE
파일시간 받아오기 함수 기술설명입니다.

### ISSUE THREAD

**Issue by hongjinhyeok** [yjosp95/Project2#3]
파일시간 받아오기 함수로는 localtime이 있습니다. 함수는 인수 timer에서 지정된 시간 값을 바탕으로 각 멤버를 적절한 값으로 초기화되어 있는 tm 구조체에 대한 포인터를 반환합니다. 이 함수가 반환된 포인터를 이용하면 시간 값에서 우리가 이해할 수 있는 시간을 표시하는 것이 가능합니다.

**Comment by kimmincheol-kor** [comment]
아아 그런게 있었군요 제가 구현할 함수에서도 유용하게 쓰일 것 같습니다.

**Comment by yjosp95** [comment]
예 알겠습니다! 진행하면 될 것 같습니다.

**Comment by Jeongyonghoon** [comment]
확인했습니다~
