### ISSUE TITLE
파일 블락 수 비교 함수 : 기술 조사

### ISSUE THREAD

**Issue by yjosp95** [yjosp95/Project2#4]
stat 구조체 중, st_blocks는 파일에 할당한 블럭의수를 의미합니다. 파일 1에 할당한 블럭의 수와 파일 2에 할당한 블럭의 수를 삼항 연산자로 비교하는 코드로 간결하게 정리하려고 합니다. 참고로 값은 integer형으로 비교합니다.

**Comment by hongjinhyeok** [comment]
block의 단위가 4k로 알고있는데 맞나요?

**Comment by Jeongyonghoon** [comment]
확인했습니다.

**Comment by kimmincheol-kor** [comment]
좋은 정보 감사합니다.

**Comment by yjosp95** [comment]
> block의 단위가 4k로 알고있는데 맞나요?

맞습니다!
