### ISSUE TITLE
4번함수에 관련한 기술조사입니다.

### ISSUE THREAD

**Issue by Jeongyonghoon** [yjosp95/Project2#6]
stat함수를 통해 가져온 정보에서 st.mtime(최종 수정시간) 멤버를
local time함수를 통해서 시간 정보를 가져올 수 있습니다.

구현 또한 위 함수를 통해 작성하겠습니다.

**Comment by hongjinhyeok** [comment]
넵 확인했습니다.

**Comment by yjosp95** [comment]
네 구현하고 이슈 부탁드립니다.

**Comment by kimmincheol-kor** [comment]
정보 감사합니다.
