### ISSUE TITLE
5번 함수에 관련한 기술조사입니다.

### ISSUE THREAD

**Issue by Jeongyonghoon** [yjosp95/Project2#7]
stat함수를 통해서 정보를 가져와 멤버에 해당하는 st.size를 통해
(int)로 형 변환 후 두 파일의크기를 쉽게 비교할 수 있습니다.

구현 또한 위 방법을 토대로 실행하겠습니다.

**Comment by yjosp95** [comment]
네 진행 부탁하겠습니다.

**Comment by hongjinhyeok** [comment]
넵 부탁드립니다.
